version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - "${MYSQL_MASTER_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}
    volumes:
      - master_data:/var/lib/mysql
      - ./init/setup_master.sh:/docker-entrypoint-initdb.d/setup_master.sh
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=${MYSQL_DATABASE}
      --bind-address=0.0.0.0
      --max_connections=1000
      --innodb_buffer_pool_size=4G
      --innodb_log_file_size=256M
      --innodb_flush_log_at_trx_commit=1
      --innodb_thread_concurrency=8
      --innodb_lock_wait_timeout=50
      --tmp_table_size=64M
      --max_heap_table_size=64M
      --table_open_cache=500
      --table_definition_cache=500
    deploy:
      resources:
        limits:
          cpus: '2.0'  # 최대 2 CPU 사용
          memory: 8G   # 최대 4GB 메모리 사용
        reservations:
          cpus: '1.0'  # 최소 1 CPU 예약
          memory: 2G   # 최소 2GB 메모리 예약
    networks:
      - mysql_cluster

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    ports:
      - "${MYSQL_SLAVE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}
    volumes:
      - slave_data:/var/lib/mysql
      - ./init/setup_slave.sh:/docker-entrypoint-initdb.d/setup_slave.sh
    depends_on:
      - mysql-master
    command: >
      --server-id=2
      --relay-log=relay-log
      --log-bin=mysql-bin
      --read-only=1
      --bind-address=0.0.0.0
      --bind-address=0.0.0.0
      --max_connections=1000
      --innodb_buffer_pool_size=4G
      --innodb_log_file_size=256M
      --innodb_flush_log_at_trx_commit=1
      --innodb_thread_concurrency=8
      --innodb_lock_wait_timeout=50
      --tmp_table_size=64M
      --max_heap_table_size=64M
      --table_open_cache=500
      --table_definition_cache=500
    deploy:
      resources:
        limits:
          cpus: '2.0'  # 최대 2 CPU 사용
          memory: 8G   # 최대 4GB 메모리 사용
        reservations:
          cpus: '1.0'  # 최소 1 CPU 예약
          memory: 2G   # 최소 2GB 메모리 예약
    networks:
      - mysql_cluster
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  master_data:
  slave_data:

networks:
  mysql_cluster:
    driver: bridge
