server:
  port: 8002

spring:
  config:
    import: "optional:envfile:.env"
  devtools:
    add-properties: false
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: master


datasource:
  master:
    url: ${SPRING_DATASOURCE_URL_MASTER}
    username: ${SPRING_DATASOURCE_USERNAME_MASTER}
    password: ${SPRING_DATASOURCE_PASSWORD_MASTER}
  slave:
    url: ${SPRING_DATASOURCE_URL_SLAVE}
    username: ${SPRING_DATASOURCE_USERNAME_SLAVE}
    password: ${SPRING_DATASOURCE_PASSWORD_SLAVE}

routing:
  datasource:
    default-target-datasource: master
    target-datasources:
      slave: slave

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
