name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행
    paths:
      - 'backend/**'  # backend 디렉토리의 파일이 변경되었을 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -p backend  # backend 디렉토리에서 빌드
        env:
          SPRING_DATASOURCE_URL_MASTER: ${{ secrets.SPRING_DATASOURCE_URL_MASTER }}
          SPRING_DATASOURCE_USERNAME_MASTER: ${{ secrets.SPRING_DATASOURCE_USERNAME_MASTER }}
          SPRING_DATASOURCE_PASSWORD_MASTER: ${{ secrets.SPRING_DATASOURCE_PASSWORD_MASTER }}
          SPRING_DATASOURCE_URL_SLAVE: ${{ secrets.SPRING_DATASOURCE_URL_SLAVE }}
          SPRING_DATASOURCE_USERNAME_SLAVE: ${{ secrets.SPRING_DATASOURCE_USERNAME_SLAVE }}
          SPRING_DATASOURCE_PASSWORD_SLAVE: ${{ secrets.SPRING_DATASOURCE_PASSWORD_SLAVE }}
          SPRING_REDIS_HOST: ${{ secrets.SPRING_REDIS_HOST }}
          SPRING_REDIS_PORT: ${{ secrets.SPRING_REDIS_PORT }}
          SPRING_ELASTICSEARCH_URIS: ${{ secrets.SPRING_ELASTICSEARCH_URIS }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Zip artifact
        run: |
          cd backend/build/libs  # JAR 파일이 있는 디렉토리로 이동
          zip -r ../backend.zip *.jar ../Procfile  # JAR 파일과 Procfile을 압축
          cd ../..  # 원래 디렉토리로 돌아감

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: '1-Backend'
          environment_name: '1-Backend-env'
          version_label: ${{ github.run_id }}
          deployment_package: backend.zip
          region: ${{ secrets.AWS_REGION }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}  # Access Key
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}  # Secret Key
