name: 게이트웨이 빌드 및 배포

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -p gateway  # gateway 디렉토리에서 빌드
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          ELASTICSEARCH_URIS: ${{ secrets.ELASTICSEARCH_URIS }}
          OAUTH2_CLIENT_KAKAO_CLIENT_ID: ${{ secrets.OAUTH2_CLIENT_KAKAO_CLIENT_ID }}
          OAUTH2_CLIENT_KAKAO_CLIENT_SECRET: ${{ secrets.OAUTH2_CLIENT_KAKAO_CLIENT_SECRET }}
          OAUTH2_CLIENT_KAKAO_REDIRECT_URI: ${{ secrets.OAUTH2_CLIENT_KAKAO_REDIRECT_URI }}
          OAUTH2_CLIENT_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH2_CLIENT_GOOGLE_CLIENT_ID }}
          OAUTH2_CLIENT_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2_CLIENT_GOOGLE_CLIENT_SECRET }}
          OAUTH2_CLIENT_GOOGLE_REDIRECT_URI: ${{ secrets.OAUTH2_CLIENT_GOOGLE_REDIRECT_URI }}
          SPRING_REDIS_HOST: ${{ secrets.SPRING_REDIS_HOST }}
          SPRING_REDIS_PORT: ${{ secrets.SPRING_REDIS_PORT }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }}
          JWT_REFRESH_TOKEN_EXPIRATION_TIME: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_TIME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: 'J4jggateway'  # Elastic Beanstalk 애플리케이션 이름
          environment_name: 'J4jggateway-env'  # Elastic Beanstalk 환경 이름
          version_label: ${{ github.run_id }}
          zip_file: gateway.zip
          region: ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
